### ISSUE TITLE
operator YAML including the status field

### ISSUE THREAD

**Issue by rienafairefr** [fluent/fluentbit-operator#118]
The fluent-bit operator setup YAML (the version I got, at https://raw.githubusercontent.com/kubesphere/fluentbit-operator/release-0.8/manifests/setup/setup.yaml) includes the status field in the resources:
```
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

AFAIK, this is not needed because the status will be set by the kube apiserver ?

With 'normal' kubectl apply it doesn't really matter, I think, but in some cases it might (I saw a problem when deploying through terraform kubernetes_manifest for example)
