### ISSUE TITLE
Quick-start doesn't take effect when have installed other logging components like logging-stack.

### ISSUE THREAD

**Issue by zhu733756** [fluent/fluentbit-operator#141]
As the title described, quick-start doesn't take effect when have installed other logging components like logging-stack.

This is not to say that there is a problem with the quick-start file, but that the name of fluentbit/fluentbitconfig and selectors is the same as logging-stack.

Since the problem occurs when applying or deleting the quick-start to the environment that has installed logging-stack or enabled KubeSphere logging components, it is not recommended to installing both components without pre-processing to the quick-start.

If you want to install both, pls do a pre-processing like follows:
```
apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit-quickstart
  namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  image: kubesphere/fluent-bit:v1.8.3
  fluentBitConfigName: fluent-bit-config-quickstart

---
apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBitConfig
metadata:
  name: fluent-bit-config-quickstart
  namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  inputSelector:
    matchLabels:
      quickstart.logging.kubesphere.io/enabled: "true"
  outputSelector:
    matchLabels:
      quickstart.logging.kubesphere.io/enabled: "true"
---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: dummy
  namespace: kubesphere-logging-system
  labels:
    quickstart.logging.kubesphere.io/enabled: "true"
spec:
  dummy:
    tag: my_dummy

---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: stdout
  namespace: kubesphere-logging-system
  labels:
    quickstart.logging.kubesphere.io/enabled: "true"
spec:
  match: "*"
  stdout: {}
```

@FeynmanZhou
