### ISSUE TITLE
Permission denied error in the setenv container

### ISSUE THREAD

**Issue by ws-prive** [fluent/fluentbit-operator#175]
Hi,

Testing this on a minikube cluster, I do see an error in the setenv container

```
+ crictl info --output go-template --template '{{.config.containerdRootDir}}'
/bin/sh: crictl: Permission denied
+ echo 'CONTAINER_ROOT_DIR='
```

minikube was started with:
```
minikube start -p k8s-test \
  --cpus 4 \
  --memory 6144 \
  --container-runtime=containerd 
```
Any idea how to fix this?

**Comment by wenchajun** [comment]
You can run the following command
```
 whereis crictl
```
Then modify the path https://github.com/fluent/fluentbit-operator/blob/master/charts/fluentbit-operator/templates/fluentbit-operator-deployment.yaml#L49 ,
change to the path you got

**Comment by ws-prive** [comment]
Hi @wenchajun,

Thanks, but my crictl is in the path from the helm-chart:

```
# whereis crictl
crictl: /usr/bin/crictl /etc/crictl.yaml /usr/local/bin/crictl
```
I think the problem is that it should be run with higher priviledges.

**Comment by wenchajun** [comment]
Could you show me your deployment yaml?
```
kubectl edit deploy fluentbit-operator -n kubesphere-logging-system
```

**Comment by ws-prive** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: fluentbit-operator
    meta.helm.sh/release-namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluentbit-operator
  name: fluentbit-operator
  namespace: kubesphere-logging-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/name: fluentbit-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: operator
        app.kubernetes.io/name: fluentbit-operator
    spec:
      containers:
      - image: kubesphere/fluentbit-operator:v0.12.0
        imagePullPolicy: IfNotPresent
        name: fluentbit-operator
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluentbit-operator
          name: env
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /bin/sh
        - -c
        - set -ex; echo CONTAINER_ROOT_DIR=$(crictl info --output go-template --template
          '{{.config.containerdRootDir}}') > /fluentbit-operator/fluent-bit.env
        image: docker:19.03
        imagePullPolicy: IfNotPresent
        name: setenv
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluentbit-operator
          name: env
        - mountPath: /var/run/containerd/containerd.sock
          name: containerdsock
          readOnly: true
        - mountPath: /usr/local/bin/crictl
          name: crictl
          readOnly: true
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: fluentbit-operator
      serviceAccountName: fluentbit-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: env
      - hostPath:
          path: /var/run/containerd/containerd.sock
          type: ""
        name: containerdsock
      - hostPath:
          path: /usr/local/bin/crictl
          type: ""
        name: crictl

```

**Comment by wenchajun** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: fluentbit-operator
    meta.helm.sh/release-namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluentbit-operator
  name: fluentbit-operator
  namespace: kubesphere-logging-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/name: fluentbit-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: operator
        app.kubernetes.io/name: fluentbit-operator
    spec:
      containers:
      - image: kubesphere/fluentbit-operator:v0.12.0
        imagePullPolicy: IfNotPresent
        name: fluentbit-operator
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluentbit-operator
          name: env
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /bin/sh
        - -c
        - set -ex; echo CONTAINER_ROOT_DIR=$(crictl info --output go-template --template
          '{{.config.containerdRootDir}}') > /fluentbit-operator/fluent-bit.env
        image: docker:19.03
        imagePullPolicy: IfNotPresent
        name: setenv
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluentbit-operator
          name: env
        - mountPath: /var/run/containerd/containerd.sock
          name: containerdsock
          readOnly: true
        - mountPath: /usr/local/bin/crictl   //change this to /usr/bin/crictl
          name: crictl
          readOnly: true
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: fluentbit-operator
      serviceAccountName: fluentbit-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: env
      - hostPath:
          path: /var/run/containerd/containerd.sock
          type: ""
        name: containerdsock
      - hostPath:
          path: /usr/local/bin/crictl  //change this to /usr/bin/crictl
          type: ""
        name: crictl
```
because your crictl path is different from the origin path,so you can change this  to solve this problem
