### ISSUE TITLE
Use k8s master URL instead of `kubernetes.default.svc`

### ISSUE THREAD

**Issue by wanjunlei** [fluent/fluentbit-operator#184]
Now the `Kubernetes` filter used the `https://kubernetes.default.svc:443` as the `Kube_URL`, so the fluent bit pod must have access to service in the default namespace.

We can use the master URL of k8s that get from the kube config file instead of the service to avoid unnecessary authorization.

```
spec:
  filters:
  - kubernetes:
      annotations: false
      kubeCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      kubeTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubeURL: https://lb.kubesphere.local:6443
      labels: false
```

There will have a DNS resolve error when using the domain, so it needed to mount the `/etc/hosts` to the fluent bit pod.

```
  volumes:
    - name: hosts
      hostPath:
        path: /etc/hosts
        type: File
```
