### ISSUE TITLE
SSL certs support for Output plugins

### ISSUE THREAD

**Issue by deveshk0** [fluent/fluentbit-operator#88]
Currently We cannot define any secrets reference in output, for some cases a ssl cert or a custom ca cert might be required to access output plugin like `kafka`, `elastic` etc. Though this can be achieved currently  mounting cert to operator itself but that looses the whole pupose of fluent bit operator where pipelines can be defined dynamically.

Is there any plan to support dynamic secrets for output plugin? A reference implementation can be found [here](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md) in Prometheus operator

**Comment by benjaminhuo** [comment]
Good point!
We currently have something relevant https://github.com/kubesphere/fluentbit-operator/blob/master/api/fluentbitoperator/v1alpha2/plugins/tls_types.go , now only the password is defined in a secret.

You mean we could put ca file in secret too?

**Comment by deveshk0** [comment]
Yes

**Comment by vincentchong1** [comment]
I will like a little bit more instruction on how to use TCP with TLS as explained above.
Follow the documented example. my deployment below work.
Which Input from the worker syslog is being written into the master specific tcp port 5170.
I will like to find out how to add the TLS.  Is that mean I can add the FluentBitSpec in the same yaml file?

`[centos@k8smaster ~]$ kubectl apply -f fluentbit-operator_tail-syslog_to-kma1-tcp.yaml
fluentbit.logging.kubesphere.io/fluent-bit created
fluentbitconfig.logging.kubesphere.io/fluent-bit-config created
input.logging.kubesphere.io/dummy created
output.logging.kubesphere.io/stdout created

[centos@k8smaster ~]$ kubectl get pod -A | grep fluent
kubesphere-logging-system   fluent-bit-8sx9w                                      1/1     Running     0          14s
kubesphere-logging-system   fluent-bit-rc6sr                                      1/1     Running     0          14s
kubesphere-logging-system   fluentbit-operator-674666fccf-695gf                   1/1     Running     0          5h51m
`
`[centos@k8smater ~]$ cat fluentbit-operator_tail-syslog_to-kma1-tcp.yaml
apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  image: kubesphere/fluent-bit:v1.8.3
  fluentBitConfigName: fluent-bit-config

---
apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBitConfig
metadata:
  name: fluent-bit-config
  namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  inputSelector:
    matchLabels:
      logging.kubesphere.io/enabled: "true"
  outputSelector:
    matchLabels:
      logging.kubesphere.io/enabled: "true"

---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: dummy
  namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
spec:
  tail:
    path: /var/log/messages
    tag: tail_var_log

---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: stdout
  namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
spec:
  tcp:
    host: <omitted>
    format: json_lines
`

**Comment by wanjunlei** [comment]
Firstly, create a secret include your tls file.

```
apiVersion: v1
data:
  ca: LS0tLS1CR
  cert: LS0tLS1C
  key: LS0tLS1C
kind: Secret
metadata:
  name: tcp-ssl
  namespace: kubesphere-logging-system
type: Opaque
```

Secondly, mount it to the operator. The files will mounted into /fluent-bit/secrets/<secret-name>

```
apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  image: kubesphere/fluent-bit:v1.8.3
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  fluentBitConfigName: fluent-bit-config
  secrets: 
     - tcp-ssl
```

Thirdly, use the tls files in the output.

```
apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: es
  namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
    logging.kubesphere.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  es:
    host: elasticsearch-logging-data.kubesphere-logging-system.svc
    port: 9200
    logstashPrefix: ks-logstash-log
    logstashFormat: true
    timeKey: "@timestamp"
    tls:
      caFile: /fluent-bit/secrets/tcp-ssl/ca
      crtFile: /fluent-bit/secrets/tcp-ssl/cert
      keyFile: /fluent-bit/secrets/tcp-ssl/key
   
```
